### ISSUE TITLE
Since version 0.3.8 photos won't load

### ISSUE THREAD

**Issue by Fleshi1981** [craibo/ha_strava#15]
In version 0.3.7 the photos worked again, but since I updated to the latest version (0.3.8) the photos from Strava won't load anymore.

**Comment by craibo** [comment]
Hi @Fleshi1981 

The 0.3.8 release was only readme file changes. 
Can you check the logs and see if there are any errors showing: https://my.home-assistant.io/redirect/logs/

This may also be caused by the changes to the callback urls in the recent core release. Ref https://github.com/home-assistant/core/pull/72449

Please try updating the domain in your Strava API configuration https://www.strava.com/settings/api to `my.home-assistant.io` and restart your home assistant. This may resolve the issue and is what I updated in the README file with the recent release

**Comment by Fleshi1981** [comment]
Hi @craibo ,

Thanks for your fast response! :) The last sollotion you suggest (changing Strava API configuration to my.home-assistant.io) was the fix 👍.

Thanks for all your good work!

**Comment by craibo** [comment]
No problem
